apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-essd
spec:
  storageClassName: alicloud-disk-essd
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: Pod
metadata:
  namespace: default
  name: nginx
spec:
  containers:
  - name: test
    image: nginx
    volumeMounts:
    - name: persistent-storage
      mountPath: /pvc
  volumes:
  - name: persistent-storage
    persistentVolumeClaim:
      claimName: pvc-essd
