apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  containers:
  - name: test1
    image: registry-vpc.cn-shanghai.aliyuncs.com/serverless-kubernetes/nginx:alpine #replace this with your private image
    imagePullPolicy: Always
  - name: test2
    image: registry.cn-shanghai.aliyuncs.com/serverless-kubernetes/tomcat #replace this with your private image
    imagePullPolicy: Always
  restartPolicy: Never
