apiVersion: v1
kind: Service
metadata:
  name: wordpress-svc
  labels:
    app: wordpress
spec:
  ports:
    - port: 80
  selector:
    app: wordpress
    tier: frontend
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress
        tier: frontend
    spec:
      containers:
      - image: registry.docker-cn.com/library/wordpress:4.8.0-apache
        name: wordpress
        env:
        - name: WORDPRESS_DB_HOST
          value: xxx.mysql.rds.aliyuncs.com              #rds instance host address
        - name: WORDPRESS_DB_PASSWORD
          value: xxx                                     #rds instance password
        ports:
        - containerPort: 80
          name: wordpress
