apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat-app
  labels:
    app: tomcat-app
spec:
  selector:
    matchLabels:
      app: tomcat-app
  template:
    metadata:
      labels:
        app: tomcat-app
    spec:
      containers:
      - name: ilogtail
        image: registry-vpc.cn-shanghai.aliyuncs.com/acs/ilogtail:0.13.4-eb42407
        env:
          - name: "ALIYUN_REGION_ID"
            value: "cn-shanghai"
          - name: "ALIYUN_LOGTAIL_USER_ID"
            value: "1851633753497255" # aliyun uid
          - name: "ALIYUN_LOGTAIL_USER_DEFINED_ID"
            value: "serverless_pods" # User-defined identity defined in Machine Group
        volumeMounts:
        - name: tomcat-log
          mountPath: /tomcat_logs
          readOnly: true
      - name: tomcat
        image: tomcat:8.5-alpine
        volumeMounts:
        - name: tomcat-log
          mountPath: /usr/local/tomcat/logs
      volumes:
      - name: tomcat-log
        emptyDir: {}
