apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-pod
  labels:
    app: ubuntu
spec:
  containers:
  - name: ubuntu
    image:  registry-vpc.cn-shanghai.aliyuncs.com/jovi/ubuntu:latest
    imagePullPolicy: Always
    command: ["sleep", "1000"]
    volumeMounts:
    - name: oss
      mountPath: "/oss"
  volumes:
  - name: "oss"
    flexVolume:
      driver: "alicloud/oss"
      options:
        bucket: "serverless-k8s"
        url: "oss-cn-shanghai.aliyuncs.com"
        akId: "xxxxx"
        akSecret: "xxxxx"
  restartPolicy: Never
