apiVersion: v1
kind: ServiceAccount
metadata:
  name: in-cluster
  namespace: default
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: in-cluster
subjects:
  - kind: ServiceAccount
    name: in-cluster
    namespace: default
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: in-cluster
spec:
  replicas: 1
  selector:
    matchLabels:
      app: in-cluster
  template:
    metadata:
      labels:
        app: in-cluster
    spec:
      serviceAccount: in-cluster
      containers:
      - name: in-cluster
        image: registry.cn-hangzhou.aliyuncs.com/serverless-kubernetes/in-cluster
      - image: ubuntu
        name: ubuntu
        command: ["sh", "-c"]
        args: ["set -x; apt-get update; apt-get install -y curl; curl -k -H \"Authorization: Bearer $(cat /var/run/secrets/kubernetes.io/serviceaccount/token)\" https://$KUBERNETES_SERVICE_HOST:6443/api/v1/namespaces/$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace)/pods; sleep 100000;"]
