apiVersion: v1
kind: Service
metadata:
  name: selenium-hub-lb
  labels:
    name: selenium-hub
spec:
  ports:
  - port: 4444
    targetPort: 4444
    name: port0
  selector:
    app: selenium-hub
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: selenium-hub
  labels:
    name: selenium-hub
spec:
  ports:
  - port: 4444
  selector:
    app: selenium-hub
  clusterIP: None
