apiVersion: apps/v1
kind: Deployment
metadata:
  name: selenium-node-firefox
  labels:
    name: selenium-node-firefox
spec:
  replicas: 1
  selector:
    matchLabels:
      name: selenium-node-firefox
  template:
    metadata:
      labels:
        name: selenium-node-firefox
    spec:
      containers:
      - name: selenium-node-firefox
        image: registry.cn-shanghai.aliyuncs.com/denverdino/selenium-node-firefox-debug:3.12.0-cobalt
        ports:
          - containerPort: 5900
        env:
          - name: HUB_PORT_4444_TCP_ADDR
            value: "selenium-hub"
          - name: HUB_PORT_4444_TCP_PORT 
            value: "4444"
        resources:
          limits:
            memory: "1000Mi"
            cpu: "0.5"