apiVersion: v1
kind: Pod
metadata:
  name: ubuntu
  labels:
    app: ubuntu
spec:
  containers:
  - name: ubuntu
    image:  ubuntu:latest
    imagePullPolicy: Always
    command: ["sh", "-c"]
    args: ["set -x; echo hello-serverless > /nas/foo; cat /nas/foo; sleep 180"]
    volumeMounts:
    - name: nas
      mountPath: "/nas"
  volumes:
  - name: nas
    nfs:
      server: ***.cn-shanghai.nas.aliyuncs.com  #NAS access address
      path: /
  restartPolicy: Never
